config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  resources :games, only: [:show] do
    resources :actions, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
  validates_uniqueness_of :abbr

  def self.all_by_grid
    empty = (0...12).to_a.map{ [nil] * 8 }
    all.inject(empty) do |grid, city|
      grid[city.y][city.x] = city
      grid
    end
  end

  def connected?(other)
    connections.split(",").include? other.name
  end

  def player_card
    Card.where(card_type: "City", name: self.name).first
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :game
  
  serialize :draw
  serialize :discard

  before_create do
    self.draw ||= []
    self.discard ||= []
  end

  def draw!
    card_id = draw.shift
    save
    Card.find(card_id)
  end

  def discard!(card)
    discard.unshift(card.id).tap { save }
  end

  def shuffle!
    self.draw = self.draw.shuffle
    save
  end

  def shuffle_discards!
    self.discard = self.discard.shuffle
    save
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :players
  has_many :viri
  has_many :decks

  belongs_to :current_player, class_name: "Player"

  def player_deck
    decks.where(name: "Player").first
  end

  def infection_deck
    decks.where(name: "Infection").first
  end

  def start!
    player_deck.shuffle!
    infection_deck.shuffle!

    3.downto(1) do |virus_count|
      3.times do
        card = infection_deck.draw!
        city = City.find_by_name(card.name)
        virus_count.times { viri.create(city: city, color: city.color) }
        infection_deck.discard!(card)
      end
    end

    self.current_player = players.first
    self.current_action = 1
    players.each do |player|
      player.draw!(player_deck.draw!)
      player.draw!(player_deck.draw!)
    end
    save
  end

  def act!
    self.current_action += 1
    end_of_turn! if current_action > current_player.actions
    save
  end

  def end_of_turn!
    draw!
    infect!
    self.current_action = 1
    players = self.players.to_a
    self.current_player = players[(players.index(current_player) + 1) % players.count]
  end

  def draw!
    current_player.draw!(player_deck.draw!)
    current_player.draw!(player_deck.draw!)
  end

  def infect!
    2.times do
      card = infection_deck.draw!
      city = City.find_by_name(card.name)
      viri.create(city: city, color: city.color)
      infection_deck.discard!(card)
    end
  end

  def treat!(city)
    return nil if viri.where(city: city).none?
    viri.where(city: city).first.destroy
    act!
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
  belongs_to :city
  belongs_to :role

  serialize :card_ids

  before_create do
    self.card_ids ||= []
  end

  def cards
    card_ids.map{|id| Card.find(id) }
  end

  def actions
    4
  end

  def current?
    game.current_player == self
  end

  def image_url
    role.image_url
  end

  def draw!(card)
    self.card_ids.push(card.id)
    # Temoprary. This should involve player interaction.
    discard! while self.card_ids.size > 7
    save
  end

  def discard!
    # TODO: Place card in player deck's discard pile
    # TODO: Human player chooses card
    self.card_ids.shift
  end

  def has_city_card?(city)
    cards.map(&:name).include? city.name
  end

  def travel_to(city)
    if can_drive?(city)
      # Drive/Ferry
      self.city = city
    elsif has_city_card?(city)
      # Fly in
      self.card_ids.delete(city.player_card.id)
      self.city = city
    elsif has_city_card?(self.city)
      # Fly out
      self.card_ids.delete(self.city.player_card.id)
      self.city = city
    end
    save
  end

  def can_drive?(city)
    return false if city == self.city
    return true if self.city.connected?(city)
  end

  def can_travel?(city)
    return true if can_drive?(city)
    return true if has_city_card?(self.city)
    return true if has_city_card?(city)
    false
  end
end

app/models/role.rb
class Role < ApplicationRecord
  def image_url
    "token/#{name.gsub(' ','')}.png"
  end
end

app/models/virus.rb
class Virus < ApplicationRecord
  belongs_to :game
  belongs_to :city
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  def create
    game = Game.find(params[:game_id])
    city = City.find(params[:city])
    player = game.current_player
    if player.can_travel? city
      player.travel_to(city)
      game.act!
    elsif player.city == city
      game.treat!(city)
    end
    redirect_back fallback_location: game_path(game)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    render
  end

  def show
    @grid = City.all_by_grid
    @players = Player.all
    render
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    render
  end

  def show
    @grid = City.all_by_grid
    @game = Game.find(params[:id])
    @players = @game.players.all
    render
  end
end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/index.haml
%h2 Current Games

%ul
  %li ...
  %li ...

app/views/games/show.haml
.board
  %table
    - @grid.each_with_index do |row, y|
      %tr
        - row.each_with_index do |city, x|
          - if city.blank?
            %td &nbsp;
          - else
            %td{class: "city #{city.color} #{'can-travel' if @players.detect(&:current?).can_travel?(city)}"}
              .players
                - @players.select{|player| player.city == city }.each do |player|
                  = render partial: 'players/pawn', locals: {player: player}

              %p= link_to city.name, game_actions_path(@game.id, city: city.id), method: :post

              .virus
                - @game.viri.where(city: city).each do |virus|
                  = image_tag "#{virus.color}.png", title: virus.color.capitalize
.card.card-block.player-card
  %h3 Players
  %table
    - @players.each do |player|
      %tr
        - if player.current?
          %td.role.current
            = player.role.name
            = render partial: 'players/pawn', locals: {player: player}
        - else
          %td.role
            = player.role.name
            = render partial: 'players/pawn', locals: {player: player}
        %td.cards
          - player.cards.each do |card|
            - if city = City.find_by_name(card.name)
              %span{class: "#{city.color}"}= city.abbr

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pandemic</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/players/_pawn.haml
- if player.current?
  = image_tag player.image_url, class: 'current', title: player.role.name
- else
  = image_tag player.image_url, title: player.role.name